resources:
  repositories:
    - repository: InfoSec_Assessments
      type: git
      name: openurls

trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/.devcontainer/Dockerfile'
        tags: |
          $(tag)

    - template: templates/install-syft-grype.yml@InfoSec_Assessments
    - template: templates/syft-grype-scan.yml@InfoSec_Assessments

    - script: |
        ls -lha $(Build.BinariesDirectory)
      displayName: 'List dir'

    - template: templates/archive-artifacts.yml@InfoSec_Assessments